---
title: "An investigation into the variables that impact mental health"
author: "Kylen Brown (3540337), Akira Govender (3540386) & Shaundre Hofstander (3540248)"
date: "29 June 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction 

An increased focus has been placed on mental health in recent times with mental health being defined according to social and individual criteria (Strupp and Hadley 1978). Society defines mental health in terms of behavioural stability whereas mental health on an individual level is associated with personal well-being (Strupp and Hadley 1978). In today’s society, it is important to examine the effects of social influences on mental health as a positive mental health is associated with the ability to be independent of social influences (Jahoda 1958). This study, therefore, aims to examine the effects of social influences including substance abuse and social support on mental health in relation to gender and age. Mental health in this study will be looked at in terms of CESD (Center for Epidemiologic Studies Depression measure at baseline) and MCS (SF-36 Mental Component Score). 

Substance abuse has negative effects on mental health as a significant percentage of suicides are related to alcohol and drug use (Wines et al. 2004). Many studies have shown that individuals with substance-related disorders exhibit increased suicidal behaviour and that depressive symptoms further increases the risk of suicidal behaviour (Darke et al. 2004; Kosten and Rounsaville 1988; Preuss et al. 2003; Wines et al. 2004). A study conducted by Cornelius et al. in 1995 showed that alcoholics who suffered from major depression were 59 % more suicidal than individuals that suffered from major depression only. In the same way that an increase in depressive symptoms is associated with suicidal behaviour, differences in suicidal behaviour also exist between substance abuse categories (Wines et al. 2004). Alcohol and CNS depressants including benzodiazepines and barbiturates increase the risk for suicidal behaviour (Wines et al. 2004). The ability of alcohol to trigger suicidal behaviour has been linked to alcohol’s ability to increase depression, facilitate aggression, decrease attention and negatively affect behaviour (Hufford 2001). 

Mental component score is an instrument of the Health-related quality of life (HRQOL) which refers to the functioning and well-being of the physical, social and mental dimensions of life (Farivar 2007). SF-36 is comprised of 8 multi-item scales averaged into two summary measures; these include the Physical (PCS) and Mental (MCS) Component Summary scores with lower Mental (MCS) Component Summary scores being indicative of worse status (Farivar 2007). In order to examine the effects of social influences on mental health, this study tests four hypotheses: (1) The effect of different substances on depressive symptoms; (2) The effect of gender on depressive symptoms; (3) The effect of different substances on Mental Component Score and (4) The influence of gender on Mental Component Score.

# Materials and methods

The data for this assignment was collected online at https://vincentarelbundock.github.io/Rdatasets/doc/mosaicData/HELPmiss.html from a study on health evaluation and linkage to primary care. In this study adult inpatients were recruited from a detoxification unit where patients with no primary care were randomized to receive multidisciplinary assessment, brief motivational intervention or usual care in order to link them to primary medical care. In this study, the eligible inpatients were adults that spoke English or Spanish, reported alcohol, heroin or cocaine as their first or second drug of choice in addition to residing in proximity to the primary care clinic to which they would be referred or were homeless. The inpatients were interviewed at the beginning of their detoxification with follow-up interviews being conducted every 6 months for a period of 2 years with a variety of continuous, count, discrete, and survival time predictors and outcomes being collected at each of these occasions. Data on age, CESD (Center for Epidemiologic Studies Depression measure at baseline), sex, suicide risk, MCS (SF-36 Mental Component Score), social support and primary substance of abuse (alcohol, cocaine or heroin) was collected for the 453 individuals that were involved in this study. In our analysis, the Mental Component Score was rounded to the nearest whole number. 

## Statistical analyses

A two-way ANOVA test was used to compare CESD (Center for Epidemiologic Studies Depression measure at baseline) between the three substances that were abused (alcohol, heroin and cocaine) and a tukey test was performed in order to identify where the differences lie. A two-way ANOVA test was used to compare the CESD (Center for Epidemiologic Studies Depression measure at baseline) between males and females with a correlation test being performed in order to measure the correlation between CESD (Center for Epidemiologic Studies Depression measure at baseline) and age. A two-way ANOVA test was used to compare MCS (SF-36 Mental Component Score) between males and females with a correlation test being performed in order to measure the correlation between MCS (SF-36 Mental Component Score) and social support. A correlation analysis was conducted to measure the correlation between MCS (SF-36 Mental Component Score) and age. A Wilcox test for non-normal data was run in order to determine the effect of CESD (Center for Epidemiologic Studies Depression measure at baseline) intensity on suicide risk. A Wilcox test for non-normal data was run in order to determine the effect of social support on suicide risk. A correlation matrix was constructed to correlate CESD (Center for Epidemiologic Studies Depression measure at baseline), age, MCS (SF-36 Mental Component Score) and social support to one another. 
